name: On push

on:
  push:

jobs:
  validate_commit_shas:
    uses: kurtismash/commit-sha-validator@master
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
