name: Sync to another org
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token for your org's repo
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
          repositories: test
          owner: kurtismash2

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: debug
        run: git branch
      
      - name: Push to target repo
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git remote add target https://x-access-token:${TOKEN}@github.com/kurtismash2/test.git
          git push target --mirror
